Automated gui test demo
tiiuae/ci-test-automation pull request #140
Opened 2024-09-19 12:42 UTC by leivos-unikie

This PR requires grim and ydotools in ghaf:
https://github.com/tiiuae/ghaf/pull/795

Proof of concept demonstration how to 
- take screenshots 
- detect image coordinates on screenshot
- move mouse to the desired location
- click mouse

In this PR the `Start Chromium on LenovoX1` test is modified in such a way that it does not use `Kill process` for closing the chromium but instead locates the close button (x) of the window, moves cursor on it and clicks. Then the test case also checks that chromium related processes were actually closed.

2024-09-24 11:10 UTC, maaharko commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
Tests shouldn't rely on each other. Now "Close Chromium via GUI on LenovoX1" test is relying on test case "Start Chromium via GUI on LenovoX1". I'd prefer to keep those as one test.

2024-09-24 11:10 UTC, maaharko commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +Close Chromium via GUI on LenovoX1
Tests shouldn't rely on each other. Now "Close Chromium via GUI on LenovoX1" test is relying on test case "Start Chromium via GUI on LenovoX1". I'd prefer to keep those as one test.

2024-09-24 11:12 UTC, maaharko commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +Library             BuiltIn
It is unnecessary to add BuiltIn library here

2024-09-24 12:00 UTC, azbeleva commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +Close Chromium via GUI on LenovoX1
Yeah it can be the one test or you can open or close the app in in different way (by console) , but tests should be independent, that's true

2024-09-27 05:43 UTC, leivos-unikie commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +Close Chromium via GUI on LenovoX1
App launch and close via GUI has been included into same test.

2024-09-27 06:06 UTC, maaharko approved these changes

2024-09-27 09:40 UTC, azbeleva commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +    Check that the application was started    ${app}
I suggest to add timeout here, by default the range is 2, but let's do it larger

2024-09-27 09:41 UTC, azbeleva commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +    Check that the application was started    ${app}
I guess we don't need additional sleep because it is inside the following keyword, you can increase the number of itterations

2024-09-27 09:42 UTC, azbeleva commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +    Check that the application is not running    ${app}
this keyword also requires iterations

2024-09-27 10:50 UTC, leivos-unikie commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +    Check that the application was started    ${app}
I put 10

2024-09-27 10:50 UTC, leivos-unikie commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +    Check that the application is not running    ${app}
iterations added

2024-09-27 10:50 UTC, leivos-unikie commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +    Check that the application was started    ${app}
Yep

2024-09-27 11:43 UTC, azbeleva commented on Robot-Framework/resources/common_keywords.resource
>      # ${out}   Run and Return RC   ping ${DEVICE_IP_ADDRESS} -c 1
commented code

2024-09-27 11:46 UTC, azbeleva commented on Robot-Framework/resources/common_keywords.resource
> +    Log To Console       ${app_name} not running
this part of code doesn't work as supposed to work
![image](https://github.com/user-attachments/assets/151ec8a7-08e6-47b9-aa9d-85dba936ebe5)

Suggested:
`    ${pids}=  Set Variable  ${EMPTY}
    FOR   ${i}   IN RANGE  ${range}
        ${keyword_status}  ${pids}  Run Keyword And Ignore Error   Find pid by name    ${app_name}
        ${status}    Run Keyword And Return Status   Should Be Empty  ${pids}
        IF    ${status}    BREAK
        Sleep   1
    END
    Should Be Empty   ${pids}   ${app_name} is still running
    Log To Console    ${app_name} not running`

2024-09-27 12:01 UTC, azbeleva commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +        Run Keyword And Ignore Error  Execute Command   -b /run/current-system/sw/bin/ydotoold --socket-path /tmp/.ydotool_socket  sudo=True  sudo_password=${PASSWORD}  timeout=3
why do we ignore error? what kind of error can occur which we want to ignore?

2024-09-30 06:45 UTC, leivos-unikie commented on Robot-Framework/resources/common_keywords.resource
>      # ${out}   Run and Return RC   ping ${DEVICE_IP_ADDRESS} -c 1
That keyword is from Maarit. I remove the line.

2024-09-30 07:55 UTC, leivos-unikie commented on Robot-Framework/resources/common_keywords.resource
> +    Log To Console       ${app_name} not running
Yes, that keyword was totally broken. Thanks.

2024-09-30 08:41 UTC, leivos-unikie commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +        Run Keyword And Ignore Error  Execute Command   -b /run/current-system/sw/bin/ydotoold --socket-path /tmp/.ydotool_socket  sudo=True  sudo_password=${PASSWORD}  timeout=3
This was a bit tricky part. The thing is that without forcing the timeout (and consequently failing the 'Execute Command' keyword) I could not make the execution to continue. Without timeout robot will just get stuck. When tried manually in gui-vm it requires one hit of enter to return to command prompt. I admit that this is not the best solution but I could not find better for now. Any suggestions?

In the current state this keyword cannot fail even if starting ydotool daemon failed for some reason. If starting the daemon didn't succeed it would show up at next `Execute Command ydotool mousemove...` which would fail. 

It's possible add 
`${ydotoold_state}=    Execute Command    sh -c 'ps aux | grep ydotoold | grep -v grep'` 
`Should Not Be Empty  ${ydotoold_state}  failed to start ydotool daemon`
also to the end of the keyword so that it would actually be able to fail if launching ydotoold didin't succeed.

2024-09-30 08:55 UTC, leivos-unikie commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +        Run Keyword And Ignore Error  Execute Command   -b /run/current-system/sw/bin/ydotoold --socket-path /tmp/.ydotool_socket  sudo=True  sudo_password=${PASSWORD}  timeout=3
I added the check that launching ydotool daemon succeeded.

2024-09-30 12:11 UTC, azbeleva commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +    BuiltIn.Sleep  1
do we still need this sleep?

2024-09-30 12:12 UTC, azbeleva commented
don't forget to squash all commits

2024-10-01 06:11 UTC, leivos-unikie commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +    BuiltIn.Sleep  1
No we don't

2024-10-02 11:55 UTC, leivos-unikie commented
Added ewwbar support also for Orin AGX.

2024-10-14 13:05 UTC, leivos-unikie commented
I had to add also automated login because now ghaf boots to login screen.

2024-10-15 06:06 UTC, maaharko commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +Login on Lenovo-X1
This logging to lenovo should be in suite setup, because it is required for next test cases. Also I think the keyword to log in to Lenovo should be somwhere in common keyword resource, since it will be needed in other tests as well

2024-10-15 07:27 UTC, leivos-unikie commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +Login on Lenovo-X1
There is also the problem that grim is not working during login screen. So we don't have any direct way to verify that login screen is ready to receive input. At boot gui-vm journalctl shows this kind of lines few seconds before the login screen appears:
```
Oct 15 09:52:12 gui-vm seatd[814]: 00:00:05.840 [INFO] [seatd/server.c:145] New client connected (pid: 907, uid: 999, gid: 998)
Oct 15 09:52:12 gui-vm seatd[814]: 00:00:05.840 [INFO] [seatd/seat.c:170] Added client 1 to seat0
Oct 15 09:52:12 gui-vm seatd[814]: 00:00:05.840 [INFO] [seatd/seat.c:480] Opened client 1 on seat0
Oct 15 09:52:14 gui-vm systemd[898]: Created slice User Core Session Slice.
Oct 15 09:52:14 gui-vm systemd[898]: Starting D-Bus User Message Bus...
Oct 15 09:52:14 gui-vm systemd[898]: Started D-Bus User Message Bus.
Oct 15 09:52:14 gui-vm dbus-daemon[920]: [session uid=999 pid=920] Successfully activated service 'org.freedesktop.systemd1'
```

But at the time when login screen appears there are no journalctl logs.

So we are doing login here blindfolded. This requires more attention when adding logout/login test. Anyway, if gui tests are run at later point ghaf should have login screen well ready.

2024-10-15 09:25 UTC, maaharko commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +Login on Lenovo-X1
`Start and close chromium via GUI on LenovoX1` and  `Start and close Firefox via GUI on Orin AGX `are depending on test `Login on Lenovo-X1`. Normally automated tests should be able to run independently. Therefore this logging should be done already in suite setup

2024-10-16 11:20 UTC, leivos-unikie commented on Robot-Framework/test-suites/bat-tests/gui-tests.robot
> +Login on Lenovo-X1
I created separate suite for gui tests. Setup of that suite includes log in and it also saves log in/out state after the boot to global variable which is then read in the test case Boot to login screen (to check it didn't boot to desktop directly).

I added log out to the Teardown of gui test suite to render the system into same state (login screen) where it is expected to be when starting the test run.

2024-10-17 10:43 UTC, maaharko commented on Robot-Framework/test-suites/gui-tests/__init__.robot
> +    Log To Console    ${logged_in_status}
Is this really working? I mean where is this variable initiated? I can see it getting value in `Verify Logout` but that is run after setup.

In general all suite and global variables should be written in upper letters to differentiate from normal variables

2024-10-17 11:09 UTC, leivos-unikie commented on Robot-Framework/test-suites/gui-tests/__init__.robot
> +    Log To Console    ${logged_in_status}
I didn't find any problem in using that ${logged_in_status}. It is initiated within the setup (line 29), not after it.

Thanks. I will change it to uppercase.

2024-10-17 11:12 UTC, leivos-unikie commented on Robot-Framework/test-suites/gui-tests/__init__.robot
> +    Log To Console    ${logged_in_status}
It seems that in this repo there are many lower case global variables. Should I change them all?

2024-10-21 12:23 UTC, azbeleva commented on Robot-Framework/test-suites/gui-tests/__init__.robot
> +    END
make it a one (or several logical) keyword, so setup could be readable

2024-10-21 12:24 UTC, azbeleva commented on Robot-Framework/test-suites/gui-tests/__init__.robot
> +    END
also I would ask you to add tabs - also for readability, something like this:
![image](https://github.com/user-attachments/assets/3b349f86-ce2a-4ad7-8d12-8ddc7f597530)

2024-10-22 06:02 UTC, maaharko commented on Robot-Framework/test-suites/gui-tests/__init__.robot
> +Run journalctl recording
We should avoid defining same keywords in several places. This keyword is defined in bat-suites init-file. Maybe that could be moved to common_keyword.resource

2024-10-22 07:33 UTC, azbeleva commented on Robot-Framework/test-suites/gui-tests/gui_apps.robot
> +    [Tags]            bat   SP-T97-1   lenovo-x1
add correct zephyr tag please (without ssrc)

2024-10-22 08:55 UTC, azbeleva commented on Robot-Framework/test-suites/gui-tests/__init__.robot
> +    Log To Console              ${LOGGED_IN_STATUS}
suggest
`Log To Console              LOGGED_IN_STATUS at start: ${LOGGED_IN_STATUS}`

2024-10-22 09:01 UTC, azbeleva commented on Robot-Framework/resources/gui_keywords.resource
> +    Type string and press enter  ghaf
use global variables ${LOGIN} and ${PASSWORD}

2024-10-22 09:09 UTC, azbeleva commented on Robot-Framework/resources/gui_keywords.resource
> +    Log To Console    Typing ${string}
let's not log it here at least for a while

2024-10-22 09:48 UTC, azbeleva commented on Robot-Framework/resources/gui_keywords.resource
> +        # Log To Console  ${locate_status}
comment

2024-10-22 09:49 UTC, azbeleva commented on Robot-Framework/test-suites/gui-tests/gui_apps.robot
> +    # ...                ${close_button}=../gui-ref-images/${app}/close_button.png
comment

2024-10-22 10:18 UTC, avnik requested changes
I suggest some changes related imagemagick, and add more notes

2024-10-22 10:18 UTC, avnik commented on flake.nix
> +          # How to add imagemagick
`imagemagick` here is enough for get im in devshell

2024-10-22 10:18 UTC, avnik commented on Robot-Framework/test-suites/gui-tests/__init__.robot
> +    ${app_icon_pack_path}   Execute Command   echo /nix/store/$(ls /nix/store | grep icon-pack | tail -1)
Running `$(ls /nix/store ...)` is pretty slow on big stores, also is indeterminism.  Could we provide path via devshell's environment variable?

2024-10-22 10:18 UTC, avnik commented on Robot-Framework/test-suites/gui-tests/__init__.robot
> +    Get icon                /run/current-system/sw/share/icons/Adwaita/symbolic/ui  window-close-symbolic  crop=0  filename=window-close
One more, could we pass adwaita as environment variable?

2024-10-22 10:18 UTC, avnik commented on Robot-Framework/lib/gui_testing.py
> +        subprocess.run(['magick', '-background', background, 'icon.svg', '-gravity', 'center', '-extent',
you perhaps probably want `convert` executable, because imagemagick haven't single `magick` executable, but bunch of tools like `convert`, `conjure`, whatever else

2024-10-23 05:40 UTC, leivos-unikie commented on flake.nix
> +          # How to add imagemagick
Indeed very simple. I had already tried that but it didn't work then. I don't know what I did differently. Now it's working.

2024-10-23 05:42 UTC, leivos-unikie commented on Robot-Framework/lib/gui_testing.py
> +        subprocess.run(['magick', '-background', background, 'icon.svg', '-gravity', 'center', '-extent',
In IMv7 convert is deprecated, the recommended use for convert is just
`magick inputfile outputfile`

2024-10-23 06:07 UTC, leivos-unikie commented on Robot-Framework/test-suites/gui-tests/__init__.robot
> +    ${app_icon_pack_path}   Execute Command   echo /nix/store/$(ls /nix/store | grep icon-pack | tail -1)
Currently the execution time of both of those `ls` commands is well below 0.04s. I don't see any problem in that. How fast should it be? 

Do you mean using some already existing environment variable or creating one?

I thought that the nix store path to that icon-pack and ghaf-artwork might be changing between builds, so we cannot hardcode a variable for them.

2024-10-23 06:10 UTC, leivos-unikie commented on Robot-Framework/test-suites/gui-tests/__init__.robot
> +    Get icon                /run/current-system/sw/share/icons/Adwaita/symbolic/ui  window-close-symbolic  crop=0  filename=window-close
I can make a variable for that adwaita path. 

Does it matter whether I am using dev shell environment variable or robot framework variable?

2024-10-23 07:48 UTC, leivos-unikie commented on Robot-Framework/test-suites/gui-tests/gui_apps.robot
> +    # ...                ${close_button}=../gui-ref-images/${app}/close_button.png
removed

2024-10-23 07:48 UTC, leivos-unikie commented on Robot-Framework/resources/gui_keywords.resource
> +        # Log To Console  ${locate_status}
debugging, reemoved

2024-10-23 07:48 UTC, leivos-unikie commented on Robot-Framework/resources/gui_keywords.resource
> +    Type string and press enter  ghaf
yes. thanks.

2024-10-23 07:48 UTC, leivos-unikie commented on Robot-Framework/test-suites/gui-tests/gui_apps.robot
> +    [Tags]            bat   SP-T97-1   lenovo-x1
changed

2024-10-23 07:49 UTC, leivos-unikie commented on Robot-Framework/test-suites/gui-tests/__init__.robot
> +    END
it's more beautiful now

2024-10-23 11:36 UTC, azbeleva commented on Robot-Framework/test-suites/gui-tests/gui_login.robot
> +    [Tags]            bat   lenovo-x1   SP-T2
remove 'bat' tag please

2024-10-23 11:36 UTC, azbeleva commented on Robot-Framework/test-suites/gui-tests/gui_login.robot
> +    [Tags]            bat   lenovo-x1   SP-T149
remove 'bat' tag please

2024-10-23 12:46 UTC, azbeleva commented on Robot-Framework/test-suites/gui-tests/gui_login.robot
I have doubt about this file. Basically you are doing log in in setup and log out in teardown, if one of the steps fails - test fails. So if there are some problems with it - you will see it. Then you have SP-T149 test case where you are doing the same actions one more time in reverse order. And I also think that SP-T2 is kind of strange, because the tested feature is included in setup. I can't say now what is the better way, but I am not sure about current implementation

2024-10-24 07:17 UTC, leivos-unikie commented on Robot-Framework/test-suites/gui-tests/gui_login.robot
Maarit suggested that login should be added to the suite setup because all gui tests depend on login. I agreed to this but the consequence is that I didn't find any other way to check 'boot to log screen' than to include it to suite setup before the initial login. However, this test can be removed if it is not considered necessary.

The drawback of failing logout in Teardown is that it infects all gui test cases with fail status. But if login is in Setup I thought we should include logout to Teardown to leave the system to the same state where it is supposed to be when starting gui test suite. 

But if we remove 'Boot to login screen' then maybe we can also remove logout from Teardown and change SP-T149 to test only logout. But then it should be ensured that this test is run last in the gui test suite.

What do you think?

2024-10-24 08:24 UTC, leivos-unikie commented on Robot-Framework/test-suites/gui-tests/gui_login.robot
Actually it now came to my mind that if we add a test case for pressing the "Reboot" button in the power menu that check for booting into login screen could be moved as part of "gui reboot" test case and the login screen state does not need to be saved in the suite Setup.

2024-10-24 08:38 UTC, azbeleva commented on Robot-Framework/test-suites/gui-tests/gui_login.robot
I like your idea with reboot, but it will check two things (reboot button and login screen), but it's okay for now

2024-10-24 08:43 UTC, leivos-unikie commented on Robot-Framework/test-suites/gui-tests/gui_login.robot
Ok. I will add that. Booting into login screen can be considered as part of successful reboot so I think it is justified.

2024-10-25 07:57 UTC, leivos-unikie commented on Robot-Framework/test-suites/gui-tests/gui_login.robot
Although login is already in suite setup (and whole suite will fail if login fails) I added Login also as a separate test case between 'GUI Reboot' and Logout since there has to be login anyway.

2024-10-25 08:03 UTC, leivos-unikie commented
When the number of GUI tests increase new `Connect to VM if not already connected` keyword can save testing time significantly by reducing the unnecessary re-connection cycles.

That keyword could potentially speed up also some currently existing test cases.

2024-10-25 10:55 UTC, azbeleva commented on Robot-Framework/test-suites/gui-tests/gui_power_options.robot
> +    Connect to VM if not already connected  gui-vm
I don't think you should actually make such checks, it's the beginning of the test and you should close connections in the end of each test and create new in new test case.
If you need to switch between connections inside of one test you can save the connection as a variable and use it in keyword 'Switch Connection'

2024-10-28 09:57 UTC, leivos-unikie commented on Robot-Framework/test-suites/gui-tests/gui_power_options.robot
> +    Connect to VM if not already connected  gui-vm
Why not to use same connection over multiple app launch test cases?

I looked the app launch tests in app.robot as a reference. They are not closing connections in the end of each test case (only the bat test suite has Close All Connections in the Common Teardown) but this causes open ssh connections to accumulate (on ghaf-host and net-vm). This can be monitored by running `watch who` in ghaf-host during test run. I just thought, instead of opening new ssh connection for each test case, to use the existing one, to prevent accumulating connections and to save some time.

Do you see some risk in using the same ssh connection over multiple tests?

2024-10-28 12:33 UTC, azbeleva commented on Robot-Framework/test-suites/gui-tests/gui_power_options.robot
> +    Connect to VM if not already connected  gui-vm
let's reconsider that later, for now merge how it is

2024-10-28 12:33 UTC, azbeleva approved these changes

2024-10-28 12:58 UTC, merged